### ISSUE TITLE
permutationTestDendrix.py 

### ISSUE THREAD

**Issue by Dickensia** [ding-lab/MuSiC2#14]
I am reading your scripts and I have something to ask: 
In line 153,
why you make this dictionary called 'sample_mutatedGenes' zero after taking a lot of effort to sort it out?

**Comment by Beifang** [comment]
Hey, Dendrix module is from Ben Raphael group (http://compbio.cs.brown.edu/projects/dendrix/). Could you please send email to Raphael lab for the algorithm details.  thanks.

**Comment by Dickensia** [comment]
Sure, thanks!
