### ISSUE TITLE
Excessive RAM usage with large ROI file.

### ISSUE THREAD

**Issue by glemmon** [ding-lab/MuSiC2#3]
We are trying to use MuSiC2 with regions of interest files that define:
1) regulatory or conserved noncoding regions
2) Transcription factor binding sites
3) DNAse hypersensitive sites

Trying the first ROI file described above. My ROI file has 1,408,562 regions of interest, but these regions contain extensive overlap. I have 120 samples.

I provide 40 GB of RAM and the process dies after hitting a swap limit of 42 GB. Now I am trying 70 GB. We only have 5 TB of shared RAM and it wouldn't be fair to other users to use all of it... Any suggestions? Why is the code using so much RAM?

**Comment by Beifang** [comment]
I have pushed an input ROI file example to github. Please compare your ROI file to the example.
