### ISSUE TITLE
typo in the CalcBmr.pm module

### ISSUE THREAD

**Issue by yulijia** [ding-lab/MuSiC2#4]
https://github.com/ding-lab/MuSiC2/blob/master/lib/TGI/MuSiC2/CalcBmr.pm

Line 113, the right parenthesis may be reported as syntax error, please remove it. Thanks.

```
my $cp_command = "cp $temp_clustering_maf_file temporary_MAF_from_mutation_cluster_function_20150121.maf" );
```

```
lab@localhost:~/MuSiC2$ music2
syntax error at /home/lab/perl5/lib/perl5/TGI/MuSiC2/CalcBmr.pm line 113, near ""cp $temp_clustering_maf_file temporary_MAF_from_mutation_cluster_function_20150121.maf" )"
Global symbol "$cp_command" requires explicit package name at /home/lab/perl5/lib/perl5/TGI/MuSiC2/CalcBmr.pm line 114.
Compilation failed in require at /home/lab/perl5/lib/perl5/TGI/MuSiC2/Bmr.pm line 8.
BEGIN failed--compilation aborted at /home/lab/perl5/lib/perl5/TGI/MuSiC2/Bmr.pm line 8.
Compilation failed in require at /home/lab/perl5/bin/music2 line 14.
BEGIN failed--compilation aborted at /home/lab/perl5/bin/music2 line 14.
```

**Comment by AdamDS** [comment]
I knocked out that right parens. Build, install, and "music2" command for help text now works on my end. Let me know if the issue persists on your end.

**Comment by yulijia** [comment]
Thanks for your reply. I remove the parens and everything is right.

By the way, is there any manual (example) of how to using music or music2?

2015-09-25 1:28 GMT+08:00 Adam D Scott <notifications@github.com>:

**Comment by yulijia** [comment]
I find the manual online. http://gmt.genome.wustl.edu/packages/genome-music/

Thanks for the great tool.
