### ISSUE TITLE
Command music2 bmr calc-covg fails

### ISSUE THREAD

**Issue by kjnousia** [ding-lab/MuSiC2#5]
The command requires optional argument "cmd-list-file" and the argument is given the resulted script is not run. The error message:
... not found in ../Data/Music/covG/output/roi_covgs. please make a command list file to run calcRoiCovg !

**Comment by AdamDS** [comment]
The error is thrown when the sample .covg file is not found. When running for the first time, you do need the cmd-list-file. If the cmd-list-file is left unspecified, then the script runs calcRoiCovg for each sample, but it will skip those samples whose output is already in roi_covgs.

**Comment by kjnousia** [comment]
Unfortunately script does not run at all if  cmd-list-file is not specified. If it is, then it indeed creates a text file but second run of music2 bmr calc-covg does not recognize the file. Moreover, when I try to run command from the created file on terminal, music does not recognize the bamfiles:

 Use of uninitialized value $normal_bam in -s at /share/apps/music2/0.1/perl5/lib/perl5/TGI/MuSiC2/CalcCovgHelper.pm line 54.
Use of uninitialized value $normal_bam in concatenation (.) or string at /share/apps/music2/0.1/perl5/lib/perl5/TGI/MuSiC2/CalcCovgHelper.pm line 54.
Normal BAM file not found or is empty: 
Use of uninitialized value $tumor_bam in -s at /share/apps/music2/0.1/perl5/lib/perl5/TGI/MuSiC2/CalcCovgHelper.pm line 55.
Use of uninitialized value $tumor_bam in concatenation (.) or string at /share/apps/music2/0.1/perl5/lib/perl5/TGI/MuSiC2/CalcCovgHelper.pm line 55.
Tumor BAM file not found or is empty: 
Use of uninitialized value $normal_bam in -s at /share/apps/music2/0.1/perl5/lib/perl5/TGI/MuSiC2/CalcCovgHelper.pm line 56.

What to do?

**Comment by MHBailey** [comment]
Sorry for the delay. 

I would check on two different aspects.
1) Make sure that you normal-tumor pairs are tab delimited. 
e.g. --normal-tumor-bam-pair="ID<\t>normal.bam<\t>tumor.bam"

Or you could start with a command similar to this. (This should generate a cmd_list_file for you)
2)music2 bmr calc-covg --bam-list <your-file-name> --output-dir . --reference-sequence refseq.fa --roi-file roi_file --cmd-prefix <your system prefix. (e.g. if LSF then you'd put bsub)> --cmd-list-file cmd_list_file

**Comment by kjnousia** [comment]
Hi,


Thank you for your help.



I managed to run music2 successfully. I just took the manual too literally and tried to use it on a system  which I had not yet configured to fit  my analysis.


Kind Regards,
Kari Nousiainen



________________________________
Lähettäjä: MHBailey <notifications@github.com>
Lähetetty: 2. joulukuuta 2016 23:48
Vastaanottaja: ding-lab/MuSiC2
Kopio: Nousiainen Kari; Author
Aihe: Re: [ding-lab/MuSiC2] Command music2 bmr calc-covg fails (#5)


Sorry for the delay.

I would check on two different aspects.

  1.  Make sure that you normal-tumor pairs are tab delimited.
e.g. --normal-tumor-bam-pair="ID<\t>normal.bam<\t>tumor.bam"

Or you could start with a command similar to this. (This should generate a cmd_list_file for you)
2)music2 bmr calc-covg --bam-list --output-dir . --reference-sequence refseq.fa --roi-file roi_file --cmd-prefix <your system prefix. (e.g. if LSF then you'd put bsub)> --cmd-list-file cmd_list_file

-
