### ISSUE TITLE
music2 smg error: Argument "Reference_Allele" isn't numeric in numeric lt (<)  

### ISSUE THREAD

**Issue by evanbiederstedt** [ding-lab/MuSiC2#7]
I get the following error running `music2 smg` on the `music2 bmr` output maf. 

```
$ music2 smg --gene-mr-file=/path/output_bmr.maf --output-file=t.txt
Argument "Reference_Allele" isn't numeric in numeric lt (<) at /path/music2/music2-0.2/lib/TGI/MuSiC2/Smg.pm line 89, <GEN0> line 1.
Argument "Variant_Classification" isn't numeric in numeric lt (<) at /path/music2/music2-0.2/lib/TGI/MuSiC2/Smg.pm line 89, <GEN0> line 1.
Unrecognized mutation category in gene-mr-file. Inappropriate ioctl for device

````

I'm not sure why this is. The MAF looks correctly formatted, and columns `Reference_Allele` and `Variant_Classification` are obviously not numeric. 

Any debugging pointers?

**Comment by Beifang** [comment]
I have pushed an input MAF file example to github. Please compare your input to this example file.
